"use server";

import { revalidatePath } from "next/cache";

import { getCurrentUser } from "@/lib/auth/current-user";
import { canViewAdmin } from "@/lib/auth/permissions";
import { getRepository } from "@/lib/repository";
import { nowIso } from "@/lib/utils";

/** Body excerpt appended to the job note when an email is linked (~500 chars). */
const NOTE_BODY_LIMIT = 500;

/**
 * Append a pasted email to the staging area (source: "paste"). Gated by
 * canViewAdmin (lead/admin). Values come from the "เพิ่มอีเมล (วางข้อความ)"
 * form; emailId/receivedAt/status are generated by the repository.
 */
export async function addEmail(formData: FormData): Promise<void> {
  const user = await getCurrentUser();
  if (!canViewAdmin(user)) {
    throw new Error("ไม่มีสิทธิ์ดำเนินการ (No permission)");
  }

  const fromAddress = String(formData.get("fromAddress") ?? "").trim();
  const subject = String(formData.get("subject") ?? "").trim();
  const body = String(formData.get("body") ?? "").trim();
  if (!fromAddress || !subject) {
    throw new Error("กรุณาระบุผู้ส่งและหัวเรื่อง");
  }

  await getRepository().appendEmail({
    fromAddress,
    subject,
    body: body || undefined,
    source: "paste",
  });
  revalidatePath("/admin/inbox");
}

/**
 * Link a staged email to an existing job: appends an ActivityLog note on the
 * job (so it shows in the job's comment/activity feed) and stamps the email
 * row as linked. Gated by canViewAdmin. Throws if the email or job is missing.
 */
export async function linkEmailToJob(emailId: string, jobId: string): Promise<void> {
  const user = await getCurrentUser();
  if (!canViewAdmin(user)) {
    throw new Error("ไม่มีสิทธิ์ดำเนินการ (No permission)");
  }

  const trimmedEmailId = emailId.trim();
  const trimmedJobId = jobId.trim();
  if (!trimmedEmailId || !trimmedJobId) {
    throw new Error("กรุณาระบุอีเมลและงานที่จะเชื่อม");
  }

  const repo = getRepository();
  const email = (await repo.listEmails()).find((e) => e.emailId === trimmedEmailId);
  if (!email) throw new Error(`ไม่พบอีเมล ${trimmedEmailId}`);
  const job = await repo.getJob(trimmedJobId);
  if (!job) throw new Error(`ไม่พบงาน ${trimmedJobId}`);

  const excerpt = email.body ? email.body.slice(0, NOTE_BODY_LIMIT) : "";
  const note = `อีเมลเข้า: ${email.subject}${excerpt ? `\n${excerpt}` : ""}`;
  await repo.addNote(trimmedJobId, note, user);

  await repo.updateEmailStatus(
    trimmedEmailId,
    {
      status: "linked",
      matchedJobId: trimmedJobId,
      handledBy: user.csId,
      handledAt: nowIso(),
    },
    user,
  );
  revalidatePath("/admin/inbox");
  revalidatePath(`/jobs/${trimmedJobId}`);
}

/** Skip a staged email (status → "ignored"). Gated by canViewAdmin. */
export async function ignoreEmail(emailId: string): Promise<void> {
  const user = await getCurrentUser();
  if (!canViewAdmin(user)) {
    throw new Error("ไม่มีสิทธิ์ดำเนินการ (No permission)");
  }

  const trimmed = emailId.trim();
  if (!trimmed) throw new Error("กรุณาระบุรหัสอีเมล");

  await getRepository().updateEmailStatus(
    trimmed,
    { status: "ignored", handledBy: user.csId, handledAt: nowIso() },
    user,
  );
  revalidatePath("/admin/inbox");
}
